postgresql/ref/pgupgrade.xml
ci-joint la proposition de traduction pour ref/pgupgrade.xml
--
Éric
=> traduction 9.5 ref/pgupgrade.xml

postgresql/json.xml
=> Oublie d'un "a"

postgresql/user-manag.xml
106 : fait -> faite
213 : traduction
481 - 522 : traduction
=> Compléter traduction user-manag

postgresql/parallel.xml
Fin relecture parallel.xml ; reformulation parallel safe/unsafe/restricted -> "à parallélisation sûre/ non sûre/restreinte"
=> Update parallel.xml (fin)

postgresql/stylesheets/global.css
See https://github.com/orgs/postgresqlfr/projects/1#card-2367734
=> Increase font size for documentation

postgresql/config.xml
Quelques corrections rapides au fil d'une recherche.
=> Quelques corrections

postgresql/pgstattuple.xml, postgresql/ref/checkpoint.xml, postgresql/ref/reindex.xml
Quelques corrections, cette fois-ci sur REINDEX, pgstattuple, et les checkpoints.
=> Corrections sur REINDEX, pgstattuple, les checkpoints

postgresql/ref/create_statistics.xml
Quelques corrections de faute de frappe, accords et autres détails
=> Relecture create_statistics.xml

www-docs.postgresql.fr/index.php, www-docs.postgresql.fr/search.php
Actuellement il n'est pas possible de faire une recherche seulement pour la version 10.
Cette PR essaie de permettre cette recherche.
=> Ajout selection version 10

postgresql/ref/pgbench.xml
Depuis l'original en version 10.4.
Essentiellement corrections de style pour l'alléger,
avec occasionnelement des fautes de frappe, une poignée de faux sens, et quelques
lignes manquantes ou probables résidus de versions antérieures
=> Relecture pgbench.xml

postgresql/ref/analyze.xml, postgresql/ref/pg_basebackup.xml, postgresql/ref/pg_verify_checksums.xml
ref/analyze.xml
ref/pg_basebackup.xml
ref/pg_verify_checksums.xml
=> Traduction v11 beta3 partie 1

postgresql/bki.xml, postgresql/btree.xml
btree.xml est pas mal compliqué à traduire.  J'ai fait du mieux que j'ai pu, mais le résultat est quand même probablement pas top :(
=> Traduction v11 de btree.xml et bki.xml

postgresql/high-availability.xml
Proposition de traduction + quelques améliorations mineures
=> Trad v14 high-availability.xml

postgresql/ref/alter_collation.xml
traduction des 2 nouveaux paragraphes, revue complète.
=> alter_collation.xml vs 14β2: 

postgresql/ref/initdb.xml
À reporter sur les versions plus anciennes ?
=> Correction traduction manquante (lines -> lignes)

postgresql/archive-modules.xml, postgresql/basic-archive.xml
Comme l'indique le titre, proposition de traduction pour les fichiers `postgresql/basic-archive.xml` et `postgresql/archive-modules.xml` :-)
=> Traduction v15 basic-archive, archive-modules

postgresql/ref/listen.xml, postgresql/syntax.xml, postgresql/user-manag.xml, postgresql/xindex.xml
Voici quelques autres traduction (hors v15).
=> Autres petits bouts traduits

postgresql/ddl.xml
J'ai relu deux fois la phrase sans comprendre , ce sera plus lisible en redoublant le verbe.
(SAV de mon c4fbd5c00)
=> postgresql/ddl.xml : répéter un verbe pour la lisibilité

postgresql/wait_event_types.xml
:partying_face: 
Avoir retrouvé l'existant a fait gagner du temps, j'ai failli me lasser.
=> wait_tvent types.xml  suite, suite et fin

postgresql/xfunc.xml
Bonjour,
J'espère que personne n'était entrain de traduire cette page... Je voulais participer un peu, mais je manque de temps, je n'ai fait qu'une page.
En espérant que ça puisse vous aider un minimum.
=> Traduction de la page xfunc

postgresql/client-auth.xml
Hello !
J'ajoute la traduction d'un fichier (j'avais écrit mon nom dans le Wiki ce coup-ci !)
Il fallait bien que j'occupe le reste de mon week-end.
En espérant avoir traduit le tout correctement.
=> Traduction française du fichier client-auth.xml
